export type ContractStatus =
  | 'PENDING_EXTERNAL_APPROVALS'
  | 'REJECTED_BY_REGISTRY'
  | 'REJECTED_BY_NOTARY'
  | 'CONFIRMED';

export const CONTRACT_STATUSES = {
  PENDING_EXTERNAL_APPROVALS: 'PENDING_EXTERNAL_APPROVALS',
  REJECTED_BY_REGISTRY: 'REJECTED_BY_REGISTRY',
  REJECTED_BY_NOTARY: 'REJECTED_BY_NOTARY',
  CONFIRMED: 'CONFIRMED',
} as const;
